### ISSUE TITLE
Test error: testInitKwargs (google.protobuf.internal.reflection_test.SerializationTest)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#37]
```
======================================================================
ERROR: testInitKwargs (google.protobuf.internal.reflection_test.SerializationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/reflection_test.py", line 2348, in testInitKwargs
    repeated_int32=[1, 2, 3])
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/python_message.py", line 315, in init
    setattr(self, field_name, field_value)
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/python_message.py", line 439, in setter
    type_checker.CheckValue(new_value)
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/type_checkers.py", line 94, in CheckValue
    raise TypeError(message)
TypeError: b'bar' has type <class 'bytes'>, but expected one of: (<class 'str'>,)
```

**Comment by ramiro** [comment]
This had been fixed in 261dce68c944a7d0de9a5eafc8ec9c43c5a1660c.
