### ISSUE TITLE
Test error: testMergeExotic (google.protobuf.internal.text_format_test.TextFormatTest)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#38]
```
======================================================================
ERROR: testMergeExotic (google.protobuf.internal.text_format_test.TextFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 306, in testMergeExotic
    text_format.Merge(text, message)
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/text_format.py", line 150, in Merge
    tokenizer = _Tokenizer(text)
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/text_format.py", line 338, in __init__
    self._lines = deque(text_message.split('\n'))
TypeError: Type str doesn't support the buffer API
```

**Comment by ramiro** [comment]
Fixed in 2d64d205defe6bfd77f9019725594ced4fa7d0e3.
