### ISSUE TITLE
Test error: testPrintNestedMessageAsOneLine (google.protobuf.internal.text_format_test.TextFormatTest)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#39]
```
======================================================================
ERROR: testPrintNestedMessageAsOneLine (google.protobuf.internal.text_format_test.TextFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 125, in testPrintNestedMessageAsOneLine
    'repeated_nested_message { bb: 42 }')
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 61, in CompareToGoldenText
    self.CompareToGoldenLines(text, golden_text.splitlines(1))
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 67, in CompareToGoldenLines
    b''.join(difflib.ndiff(golden_lines, actual_lines)))
TypeError: sequence item 0: expected bytes, str found
```

**Comment by ramiro** [comment]
Fixed in 6cda8721384c9a04ca56f6164d8030f0a2adf7b0.
