### ISSUE TITLE
Test error: testPrintMessageSet (google.protobuf.internal.text_format_test.TextFormatTest)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#53]
```
======================================================================
ERROR: testPrintMessageSet (google.protobuf.internal.text_format_test.TextFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 90, in testPrintMessageSet
    'message_set {\n'
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 61, in CompareToGoldenText
    self.CompareToGoldenLines(text, golden_text.splitlines(1))
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 67, in CompareToGoldenLines
    b''.join(difflib.ndiff(golden_lines, actual_lines)))
  File "/usr/lib/python3.2/difflib.py", line 926, in compare
    for line in g:
  File "/usr/lib/python3.2/difflib.py", line 979, in _fancy_replace
    cruncher.set_seq2(bj)
  File "/usr/lib/python3.2/difflib.py", line 282, in set_seq2
    self.__chain_b()
  File "/usr/lib/python3.2/difflib.py", line 324, in __chain_b
    if isjunk(elt):
  File "/usr/lib/python3.2/difflib.py", line 1144, in IS_CHARACTER_JUNK
    return ch in ws
TypeError: 'in <string>' requires string as left operand, not int
```

**Comment by dmoisset** [comment]
Esto se arreglo con algun otro fix, ya no pasa
