### ISSUE TITLE
Errors/failures related to _Tokenizer.AtEnd()

### ISSUE THREAD

**Issue by juannorris** [machinalis/protobuf-python3#55]
## ERROR: testSimpleTokenCases (google.protobuf.internal.text_format_test.TokenizerTest)

Traceback (most recent call last):
  File "/home/jnorris/projects/3k-protobuf/python/google/protobuf/internal/text_format_test.py", line 499, in testSimpleTokenCases
    m = methods[i]
IndexError: list index out of range
## FAIL: testConsumeIntegers (google.protobuf.internal.text_format_test.TokenizerTest)

Traceback (most recent call last):
  File "/home/jnorris/projects/3k-protobuf/python/google/protobuf/internal/text_format_test.py", line 525, in testConsumeIntegers
    self.assertTrue(tokenizer.AtEnd())
AssertionError: False is not true

**Comment by juannorris** [comment]
Fixed in cf3c2353d6009f46c1d4bcd737570bbbbece6b78.
