### ISSUE TITLE
Test Failure: testMergeGroupNotClosed (google.protobuf.internal.text_format_test.TextFormatTest)

### ISSUE THREAD

**Issue by dmoisset** [machinalis/protobuf-python3#58]
```
======================================================================
FAIL: testMergeGroupNotClosed (google.protobuf.internal.text_format_test.TextFormatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 412, in assertRaisesWithMessage
    func(*args, **kwargs)
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/text_format.py", line 157, in Merge
    _MergeField(tokenizer, message)
google.protobuf.text_format.ParseError: 1:16 : Expected "b'>'".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 367, in testMergeGroupNotClosed
    text_format.Merge, text, message)
  File "/home/dmoisset/canonical/protobuf/python/google/protobuf/internal/text_format_test.py", line 418, in assertRaisesWithMessage
    e.encode('unicode_escape')))
AssertionError: ParseError raised, but with wrong message: "b'1:16 : Expected "b\'>\'".'" instead of "b'1:16 : Expected ">".'"

----------------------------------------------------------------------
```

**Comment by dmoisset** [comment]
Fixed in 31b7f05
